const express = require('express');
const PDFDocument = require('pdfkit');
const { requireAuth } = require('../middleware/auth');
const { buildPublicQrAssets } = require('../utils/public-qr');

const router = express.Router();

function dataUrlToBuffer(dataUrl) {
    const base64 = String(dataUrl || '').split(',')[1] || '';
    return Buffer.from(base64, 'base64');
}

function drawQrPage(doc, item) {
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;

    doc.font('Helvetica-Bold')
        .fontSize(24)
        .fillColor('#111827')
        .text(item.label, 0, 60, { align: 'center' });

    const qrSize = 260;
    const qrX = (pageWidth - qrSize) / 2;
    const qrY = 120;

    doc.roundedRect(qrX - 18, qrY - 18, qrSize + 36, qrSize + 36, 18)
        .fillAndStroke('#ffffff', '#e5e7eb');

    doc.image(dataUrlToBuffer(item.qrDataUrl), qrX, qrY, { width: qrSize, height: qrSize });

    doc.font('Helvetica')
        .fontSize(12)
        .fillColor('#374151')
        .text('Scan this QR code to open the form.', 0, qrY + qrSize + 40, { align: 'center' });

    doc.font('Helvetica-Bold')
        .fontSize(11)
        .fillColor('#2563eb')
        .text(item.url, 60, qrY + qrSize + 68, { align: 'center' });

    doc.font('Helvetica')
        .fontSize(10)
        .fillColor('#6b7280')
        .text('Generated by AttendIT', 0, pageHeight - 60, { align: 'center' });
}

async function buildItems(req) {
    const publicBaseUrl = process.env.PUBLIC_BASE_URL || `${req.protocol}://${req.get('host')}`;
    const { registerUrl, registerQrDataUrl, publicAttendanceLinks } = await buildPublicQrAssets(publicBaseUrl);

    return [
        {
            key: 'register',
            label: 'Student Register',
            url: registerUrl,
            qrDataUrl: registerQrDataUrl
        },
        ...publicAttendanceLinks
    ];
}

router.get('/qr/print', requireAuth, async (req, res) => {
    try {
        const items = await buildItems(req);
        res.render('public/qr-preview', {
            items,
            pdfUrl: '/qr/print.pdf'
        });
    } catch (err) {
        res.status(500).render('error', { message: err.message });
    }
});

router.get('/qr/print.pdf', requireAuth, async (req, res) => {
    try {
        const items = await buildItems(req);

        const doc = new PDFDocument({ size: 'A4', margin: 40, autoFirstPage: false });
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename="attendit-qr-cards.pdf"');
        doc.pipe(res);

        items.forEach((item, index) => {
            doc.addPage();
            drawQrPage(doc, item);
        });

        doc.end();
    } catch (err) {
        res.status(500).send(err.message);
    }
});

module.exports = router;
